# Generated by Django 4.2.4 on 2023-12-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tutor', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/course')),
                ('video_file', models.FileField(upload_to='courses/course')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=2)),
                ('students', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category')),
            ],
        ),
    ]
